### ISSUE TITLE
Problem with eas build, buildPriority must be one of [low, normal, high]

### ISSUE THREAD

**Issue by Nautman** [expo/eas-cli#1188]
Hi,

I think perhaps there may be a server-side error similar to #1026. This is my error

```
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Uploaded to EAS 3s
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, please report the issue.
    CombinedError: [GraphQL] "job" is malformed: "buildPriority" must be one of [low, normal, high]
```

Please excuse me for not following your template issues. If you insist I do that then I will, but I followed my gut feeling that it isn't necessarily an issue just for me.

For what it's worth, here is the output of `expo doctor`:
```
✔ Found all copies of expo-modules-autolinking
  All copies of expo-modules-autolinking satisfy ~0.8.1 || ~0.9.0
✔ Found all copies of @expo/config-plugins
  All copies of @expo/config-plugins satisfy ^4.1.0
✔ Found all copies of @expo/prebuild-config
  All copies of @expo/prebuild-config satisfy ^4.0.0

🎉 Didn't find any issues with the project!
```

Thank you in advance for your kind help.

**Comment by MylchenkoAlexandr** [comment]
does anyone know what's wrong? yesterday everything was work fine.
`npm i -g eas-cli@latest` not help for me.

![image](https://user-images.githubusercontent.com/45290075/176658423-3184db4a-8bac-4b7e-acb4-ab6467074285.png)

**Comment by dsokal** [comment]
Hi, sorry for the inconvenience. Can you please try running your builds now? We have just deployed a fix to our servers.

**Comment by bukky300** [comment]
<img width="690" alt="Screenshot 2022-06-30 at 12 40 54" src="https://user-images.githubusercontent.com/65443492/176668818-570db9de-b1b1-419f-b8f4-a8e632931246.png">
I'm getting unexpected server error

**Comment by bukky300** [comment]
it's working now

**Comment by Nautman** [comment]
I'm still getting your error of `Expo error ID: undefined` @bukky300 @dsokal . Are you sure that it's working for you @bukky300?

I can try again soon.

**Comment by bukky300** [comment]
yea I ran `npm i -g eas-cli@latest` before running build

**Comment by Nautman** [comment]
Okay thanks. I seem to be past the error and it says that the `Build is waiting to enter the queue.`.

I just hope that the previous errors didn't cause any problems where it thinks something is in the queue while in fact there isn't.

**Comment by dsokal** [comment]
I'm closing the issue for now. Let me know if something still doesn't work.

**Comment by MylchenkoAlexandr** [comment]
> I'm closing the issue for now. Let me know if something still doesn't work.

problem still exists.
assembly thinks there are some queues now.

![image](https://user-images.githubusercontent.com/45290075/176677412-3a4000f3-e620-4289-96df-963fa636d1ec.png)

**Comment by Nautman** [comment]
Check the builds tab @MylchenkoAlexandr . I found several loading builds there. I cancelled all of them except the one I wanted to build.

**Comment by MylchenkoAlexandr** [comment]
> Check the builds tab @MylchenkoAlexandr . I found several loading builds there. I cancelled all of them except the one I wanted to build.

I removed all my project(s) from account and restart project building. But i still see the message "You have reached the concurrency limit". But i not have any queue(s).

**Comment by Nautman** [comment]
Glad to hear things worked out :) @MylchenkoAlexandr
