### ISSUE TITLE
Authentication with Apple Developer Portal failed! [Select a Provider]

### ISSUE THREAD

**Issue by lucksp** [expo/eas-cli#2770]
### Summary

In the last 3 days, even since #2712 was marked as completed, and after updating eas-cli, I am unable to send an iOS build to EAS.  The failure seems to happen on the `Select a Provider` step.

### Managed or bare?

bare

### Environment

info:
```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/lucksp/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.11 => 0.18.11
      expo: ~51.0.39 => 51.0.39
      expo-router: ~3.5.24 => 3.5.24
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 14.1.0
    Expo Workflow: bare
```

doctor:
```
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Error output

```
npx eas build --profile production
✔ Select platform › iOS
The EAS build profile does not specify a Node.js version. Using the version specified in .nvmrc: lts/iron
The field "cli.appVersionSource" is not set, but it will be required in the future. Learn more
We detected that you are building for the "store" distribution. Resolving the environment for environment variables used during the build to "production". Set the "environment" field in the build profile if you want to specify the environment manually.
No environment variables with visibility "Plain text" and "Sensitive" found for the "production" environment on EAS servers.
Environment variables loaded from the "production" build profile "env" configuration: appName, bundleIdentifier.

The field "cli.appVersionSource" is not set, but it will be required in the future. Learn more
✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … email@gmail.com
› Restoring session /Users/me/.app-store/auth/email@gmail.com/cookie
› Session expired Local session
› Using password for email@gmail.com from your local Keychain
  Learn more
✔ Logged in New session
✔ Select a Team › IdentaFly LLC - Company/Organization (XXXXX)
✔ Select a Provider › IdentaFly LLC (XXXXX)
✖ Couldn't switch to provider IdentaFly LLC (XXXXX)
Authentication with Apple Developer Portal failed!
Apple 401 detected - You are either not logged in, your account doesn't have access to the requested data, or the page doesn't exist
    Error: build command failed.
```

### Reproducible demo or steps to reproduce from a blank project

```
`npx eas build --profile production`
`yarn eas build --platform`
```

- I also checked to make sure I am on the latest `eas-cli` version.
- I tried logging in & out from EAS server too

**Comment by szdziedzic** [comment]
It should be fixed by https://github.com/expo/eas-cli/pull/2769 in `14.2.0`. Apple changed the required payload for the provider switching endpoint and broke it in EAS CLI.

**Comment by lucksp** [comment]
> It should be fixed by #2769 in `14.2.0`. Apple changed the required payload for the provider switching endpoint and broke it in EAS CLI.

thanks for quick response @szdziedzic - when wil 14.2.0 be available for install?

**Comment by szdziedzic** [comment]
It should be released few minutes ago

**Comment by csulit** [comment]
Still failing.

![image](https://github.com/user-attachments/assets/a08fc82b-933d-460f-b8fe-c0c1148c0139)
![image](https://github.com/user-attachments/assets/333eed33-f5df-462f-8b34-f8420ebf3364)
