### ISSUE TITLE
v15+ seems to break eas build

### ISSUE THREAD

**Issue by superdopey** [expo/eas-cli#2882]
### Build/Submit details page URL

https://expo.dev/accounts/superdopey/projects/topr-pay/builds/2090b375-36de-435d-91c8-983bae11681c

### Summary

I upgraded eas-cli from v14.7.1 to v15.0.4

Afterwards my EAS builds fail, whereas before they would build fine. I reverted back to v14.7.1 again, EAS builds work again.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.2.2 environment info:
    System:
      OS: Windows 11 10.0.22635
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ~52.0.30 => 52.0.30 
      expo-router: ~4.0.17 => 4.0.17 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: lucide-react-native, react-native-nfc-manager
Unmaintained: react-native-event-listeners, redux-persist
No metadata available: @expo/html-elements, @gluestack-ui/accordion, @gluestack-ui/actionsheet, @gluestack-ui/alert, @gluestack-ui/alert-dialog, @gluestack-ui/avatar, @gluestack-ui/button, @gluestack-ui/checkbox, @gluestack-ui/divider, @gluestack-ui/fab, @gluestack-ui/form-control, @gluestack-ui/icon, @gluestack-ui/image, @gluestack-ui/input, @gluestack-ui/link, @gluestack-ui/menu, @gluestack-ui/modal, @gluestack-ui/nativewind-utils, @gluestack-ui/overlay, @gluestack-ui/popover, @gluestack-ui/pressable, @gluestack-ui/progress, @gluestack-ui/radio, @gluestack-ui/select, @gluestack-ui/slider, @gluestack-ui/spinner, @gluestack-ui/switch, @gluestack-ui/textarea, @gluestack-ui/toast, @gluestack-ui/tooltip, @hookform/resolvers, @legendapp/motion, async-mutex, eventemitter3, tailwindcss
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

### Reproducible demo or steps to reproduce from a blank project

- create expo project
- install eas-cli v15.0.4
- eas init
- eas build --profile preview --platform android

**Comment by sjchmiela** [comment]
Hey, thanks for the report. Looks like since v15 on Windows we don't ignore the `.gitignore`d files properly which causes whole `node_modules` to get packaged into the tarball. Then `node_modules/expo/bin/expo` is missing right permissions because permissioning system on Windows and on Linux is different.

Looking into it. Sorry for the trouble of having to figure out v15 broke your setup.

**Comment by sjchmiela** [comment]
Hi @superdopey. I think I have a fix for `eas-cli` v15 on Windows.

Can you please:
- add `"requireCommit": true` to `eas.json`
- ensure you don't have `.easignore` (use `.gitignore` instead)
- commit changes
- try again with latest `eas-cli` (15.0.5)?

According to my testing `node_modules` should no longer be included in the project tarball which should fix the problem of non-executable `expo`. It wasn't executable, because it wasn't being installed on Linux / macOS as part of the build process — instead, it was a copy of `node_modules` installed on your Windows machine which wasn't executable by Unix standards.

**Comment by matejkriz** [comment]
Hi @sjchmiela, we are probably facing the same issue (but it might be a different issue related to the same change). Since eas-cli@15 our builds on GitHub CI started failing with this error:

```
Compressing project files
  Failed to upload the project tarball to EAS Build
  Reason: git clone --no-hardlinks --depth 1 file:///home/runner/work/trezor-suite/trezor-suite /tmp/runner/eas-cli-nodejs/99239adc-aafd-423b-a1d7-a7481fa45c7e-shallow-clone exited with non-zero code: 128
```

I guess it's because node_module files.

I also tried it now with eas-cli@15.0.6, requireCommit: true and .easignore deleted with the same result: 
https://github.com/trezor/trezor-suite/actions/runs/13202413750/job/36857408021?pr=16892#step:7:3074

**Comment by georgehap2** [comment]
@sjchmiela Thank you so much, i started going crazy.
And just to mention that this started couple of days ago.

Anyhow, great fix!

**Comment by LeonardoNoroWidelab** [comment]
Hi, I had to install the eas-cli@14.7.1 to fix it
Seens every version of eas-cli@15 is with this issue.

**Comment by AllyssonCidade** [comment]
I had the same problem. Downgrading to eas-cli@14.7.1 worked as a workaround. I didn't try adding recommended "requireCommit": true to the eas.json cli object as mentioned above.

**Comment by sjchmiela** [comment]
Hey, `eas-cli@15.0.9` should fix the issues on Windows even if you don't have `requireCommit: true` in `eas.json`.

Make sure to:
- run `npm i -g eas-cli` to install latest version f you use `eas-cli` installed globally (use `eas`)
- `npx eas-cli`, `npx -y eas-cli` or `npx -y eas-cli@latest` if you run it through `npx`.

Please let me know if `node_modules` are still being included or you see the `sh: 1: expo: Permission denied` error. Run EAS with `--version` to verify what version you're on.

**Comment by Eiyel24** [comment]
@sjchmiela
@superdopey 
@sjchmiela  
@LeonardoNoroWidelab 
I'm having issues with splashscreen_logo. I delete it, change it, modify the entire configuration, and remove it from app.json. I replace the PNG image, and it still loads splashscreen_logo, but the error persists. What solution can you provide me, please?

PS C:\Users\User\Documents\actpro\InventoryApp> npx expo-doctor      
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

Running 'gradlew :app:assembleRelease' in /home/expo/workingdir/build/android
Welcome to Gradle 8.10.2!
Here are the highlights of this release:
- Support for Java 23
 - Faster configuration cache
- Better configuration cache reports
For more details see https://docs.gradle.org/8.10.2/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
> Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:settings-plugin:pluginDescriptors
> Task :gradle-plugin:settings-plugin:processResources
> Task :gradle-plugin:shared:processResources NO-SOURCE
> Task :gradle-plugin:shared:compileKotlin
> Task :gradle-plugin:shared:compileJava NO-SOURCE
> Task :gradle-plugin:shared:classes UP-TO-DATE
> Task :gradle-plugin:shared:jar
> Task :gradle-plugin:settings-plugin:compileKotlin
> Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:settings-plugin:classes
> Task :gradle-plugin:settings-plugin:jar
> Task :gradle-plugin:react-native-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-launcher-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :expo-updates-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-launcher-gradle-plugin:pluginDescriptors
> Task :expo-updates-gradle-plugin:pluginDescriptors
> Task :expo-dev-launcher-gradle-plugin:processResources
> Task :expo-updates-gradle-plugin:processResources
> Task :gradle-plugin:react-native-gradle-plugin:pluginDescriptors
> Task :gradle-plugin:react-native-gradle-plugin:processResources
> Task :gradle-plugin:react-native-gradle-plugin:compileKotlin
> Task :gradle-plugin:react-native-gradle-plugin:compileJava
NO-SOURCE
> Task :gradle-plugin:react-native-gradle-plugin:classes
> Task :gradle-plugin:react-native-gradle-plugin:jar
> Task :expo-updates-gradle-plugin:compileKotlin
> Task :expo-updates-gradle-plugin:compileJava NO-SOURCE
> Task :expo-updates-gradle-plugin:classes
> Task :expo-updates-gradle-plugin:jar
> Task :expo-dev-launcher-gradle-plugin:compileKotlin
> Task :expo-dev-launcher-gradle-plugin:compileJava NO-SOURCE
> Task :expo-dev-launcher-gradle-plugin:classes
> Task :expo-dev-launcher-gradle-plugin:jar
> Configure project :app
 ℹ️  [33mApplying gradle plugin[0m '[32mexpo-dev-launcher-gradle-plugin[0m' (expo-dev-launcher@5.0.27)
 ℹ️  [33mApplying gradle plugin[0m '[32mexpo-updates-gradle-plugin[0m' (expo-updates@0.26.17)
> Configure project :expo
Using expo modules
  - [32mexpo-application[0m (6.0.2)
  - [32mexpo-asset[0m (11.0.3)
  - [32mexpo-barcode-scanner[0m (14.0.1)
  - [32mexpo-camera[0m (16.0.15)
  - [32mexpo-constants[0m (17.0.5)
  - [32mexpo-crypto[0m (14.0.2)
  - [32mexpo-dev-client[0m (5.0.11)
  - [32mexpo-dev-launcher[0m (5.0.27)
  - [32mexpo-dev-menu[0m (6.0.18)
  - [32mexpo-eas-client[0m (0.13.2)
  - [32mexpo-file-system[0m (18.0.10)
  - [32mexpo-font[0m (13.0.3)
  - [32mexpo-image-loader[0m (5.0.0)
- [32mexpo-image-picker[0m (16.0.5)
  - [32mexpo-json-utils[0m (0.14.0)
  - [32mexpo-keep-awake[0m (14.0.2)
  - [32mexpo-linking[0m (7.0.5)
  - [32mexpo-manifests[0m (0.15.5)
  - [32mexpo-modules-core[0m (2.2.1)
  - [32mexpo-print[0m (14.0.3)
  - [32mexpo-sharing[0m (13.0.1)
  - [32mexpo-structured-headers[0m (4.0.0)
  - [32mexpo-updates[0m (0.26.17)
  - [32mexpo-web-browser[0m (14.0.2)
> Configure project :react-native-reanimated
Android gradle plugin: 8.6.0
Gradle: 8.10.2
> Task :expo-asset:preBuild UP-TO-DATE
> Task :expo-application:preBuild UP-TO-DATE
> Task :expo-application:preReleaseBuild UP-TO-DATE
> Task :expo-asset:preReleaseBuild UP-TO-DATE
> Task :app:checkKotlinGradlePluginConfigurationErrors
> Task :expo-application:writeReleaseAarMetadata
> Task :expo-asset:writeReleaseAarMetadata
> Task :expo-barcode-scanner:preBuild UP-TO-DATE
> Task :expo-camera:preBuild UP-TO-DATE
> Task :expo-camera:preReleaseBuild UP-TO-DATE
> Task :expo-barcode-scanner:preReleaseBuild UP-TO-DATE
> Task :app:generateAutolinkingPackageList
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :expo-barcode-scanner:writeReleaseAarMetadata
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:preBuild
> Task :expo-camera:writeReleaseAarMetadata
> Task :expo-crypto:preBuild UP-TO-DATE
> Task :expo-crypto:preReleaseBuild UP-TO-DATE
> Task :app:preReleaseBuild
> Task :expo-crypto:writeReleaseAarMetadata
> Task :expo-dev-client:preBuild UP-TO-DATE
> Task :expo-dev-client:preReleaseBuild UP-TO-DATE
> Task :expo-dev-client:writeReleaseAarMetadata
> Task :expo-dev-launcher:preBuild UP-TO-DATE
> Task :expo-dev-launcher:preReleaseBuild UP-TO-DATE
> Task :expo-dev-launcher:writeReleaseAarMetadata
> Task :expo-dev-menu:preBuild UP-TO-DATE
> Task :expo-dev-menu:preReleaseBuild UP-TO-DATE
> Task :app:generateReleaseBuildConfig
> Task :expo-dev-menu-interface:preBuild UP-TO-DATE
> Task :expo-dev-menu-interface:preReleaseBuild UP-TO-DATE
> Task :expo-dev-menu:writeReleaseAarMetadata
> Task :expo-eas-client:preBuild UP-TO-DATE
> Task :expo-eas-client:preReleaseBuild UP-TO-DATE
> Task :expo-eas-client:writeReleaseAarMetadata
> Task :expo-dev-menu-interface:writeReleaseAarMetadata
> Task :expo-font:preBuild UP-TO-DATE
> Task :expo-font:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:preBuild UP-TO-DATE
> Task :expo-file-system:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:writeReleaseAarMetadata
> Task :expo-font:writeReleaseAarMetadata
> Task :expo-image-loader:preBuild UP-TO-DATE
> Task :expo-image-picker:preBuild UP-TO-DATE
> Task :expo-image-picker:preReleaseBuild UP-TO-DATE
> Task :expo-image-loader:preReleaseBuild UP-TO-DATE
> Task :expo-image-loader:writeReleaseAarMetadata
> Task :expo-image-picker:writeReleaseAarMetadata
> Task :expo-json-utils:preBuild UP-TO-DATE
> Task :expo-keep-awake:preBuild UP-TO-DATE
> Task :expo-keep-awake:preReleaseBuild UP-TO-DATE
> Task :expo-json-utils:preReleaseBuild UP-TO-DATE
> Task :expo-keep-awake:writeReleaseAarMetadata
> Task :expo-linking:preBuild UP-TO-DATE
> Task :expo-json-utils:writeReleaseAarMetadata
> Task :expo-linking:preReleaseBuild UP-TO-DATE
> Task :expo-manifests:preBuild UP-TO-DATE
> Task :expo-manifests:preReleaseBuild UP-TO-DATE
> Task :expo-linking:writeReleaseAarMetadata
> Task :expo-modules-core:preBuild UP-TO-DATE
> Task :expo-manifests:writeReleaseAarMetadata
> Task :expo-print:preBuild UP-TO-DATE
> Task :expo-print:preReleaseBuild UP-TO-DATE
> Task :expo-modules-core:preReleaseBuild UP-TO-DATE
> Task :expo-print:writeReleaseAarMetadata
> Task :expo-sharing:preBuild UP-TO-DATE
> Task :expo-sharing:preReleaseBuild UP-TO-DATE
> Task :expo-modules-core:writeReleaseAarMetadata
> Task :expo-structured-headers:preBuild UP-TO-DATE
> Task :expo-structured-headers:preReleaseBuild UP-TO-DATE
> Task :expo-structured-headers:writeReleaseAarMetadata
> Task :expo-sharing:writeReleaseAarMetadata
> Task :expo-updates-interface:preBuild UP-TO-DATE
> Task :expo-updates:preBuild UP-TO-DATE
> Task :expo-updates:preReleaseBuild UP-TO-DATE
> Task :expo-updates-interface:preReleaseBuild UP-TO-DATE
> Task :expo-updates-interface:writeReleaseAarMetadata
> Task :expo-updates:writeReleaseAarMetadata
> Task :expo-web-browser:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :expo-web-browser:preReleaseBuild
UP-TO-DATE
> Task :react-native-gesture-handler:preReleaseBuild
UP-TO-DATE
> Task :react-native-gesture-handler:writeReleaseAarMetadata
> Task :expo-web-browser:writeReleaseAarMetadata
> Task :react-native-picker_picker:preBuild UP-TO-DATE
> Task :react-native-picker_picker:preReleaseBuild UP-TO-DATE
> Task :react-native-reanimated:assertLatestReactNativeWithNewArchitectureTask SKIPPED
> Task :react-native-reanimated:assertMinimalReactNativeVersionTask SKIPPED
> Task :expo-constants:createExpoConfig
> Task :react-native-picker_picker:writeReleaseAarMetadata
The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set.
Proceeding without mode-specific .env
> Task :expo-constants:preBuild
> Task :expo-constants:preReleaseBuild
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preReleaseBuild UP-TO-DATE
> Task :expo-constants:writeReleaseAarMetadata
> Task :react-native-screens:preBuild UP-TO-DATE
> Task :react-native-screens:preReleaseBuild UP-TO-DATE
> Task :react-native-safe-area-context:writeReleaseAarMetadata
> Task :react-native-svg:preBuild UP-TO-DATE
> Task :react-native-svg:preReleaseBuild UP-TO-DATE
> Task :react-native-svg:writeReleaseAarMetadata
> Task :react-native-vector-icons:preBuild UP-TO-DATE
> Task :react-native-vector-icons:preReleaseBuild UP-TO-DATE
> Task :react-native-screens:writeReleaseAarMetadata
> Task :react-native-vector-icons:writeReleaseAarMetadata
> Task :expo-application:generateReleaseResValues
> Task :react-native-reanimated:prepareReanimatedHeadersForPrefabs
> Task :expo-application:generateReleaseResources
> Task :react-native-reanimated:prepareWorkletsHeadersForPrefabs
> Task :react-native-reanimated:preBuild
> Task :react-native-reanimated:preReleaseBuild
> Task :react-native-reanimated:writeReleaseAarMetadata
> Task :expo-asset:generateReleaseResValues
> Task :expo-asset:generateReleaseResources
> Task :expo-asset:packageReleaseResources
> Task :expo-application:packageReleaseResources
> Task :expo-camera:generateReleaseResValues
> Task :expo-barcode-scanner:generateReleaseResValues
> Task :expo-barcode-scanner:generateReleaseResources
> Task :expo-camera:generateReleaseResources
> Task :expo-barcode-scanner:packageReleaseResources
> Task :expo-constants:generateReleaseResValues
> Task :expo-camera:packageReleaseResources
> Task :expo-crypto:generateReleaseResValues
> Task :expo-constants:generateReleaseResources
> Task :expo-crypto:generateReleaseResources
> Task :expo-constants:packageReleaseResources
> Task :expo-crypto:packageReleaseResources
> Task :expo-dev-client:generateReleaseResValues
> Task :expo-dev-client:generateReleaseResources
> Task :expo-dev-launcher:generateReleaseResValues
> Task :expo-dev-launcher:generateReleaseResources
> Task :expo-dev-client:packageReleaseResources
> Task :expo-dev-menu:generateReleaseResValues
> Task :expo:generateExpoModulesPackageListTask
> Task :expo:preBuild
> Task :expo:preReleaseBuild
> Task :expo:writeReleaseAarMetadata
> Task :expo:generateReleaseResValues
> Task :expo-dev-menu:generateReleaseResources
> Task :expo:generateReleaseResources
> Task :expo:packageReleaseResources
> Task :expo-dev-menu-interface:generateReleaseResValues
> Task :expo-dev-menu-interface:generateReleaseResources
> Task :expo-dev-menu-interface:packageReleaseResources
> Task :expo-eas-client:generateReleaseResValues
> Task :expo-eas-client:generateReleaseResources
> Task :expo-eas-client:packageReleaseResources
> Task :expo-file-system:generateReleaseResValues
> Task :expo-file-system:generateReleaseResources
> Task :expo-dev-menu:packageReleaseResources
> Task :expo-font:generateReleaseResValues
> Task :expo-font:generateReleaseResources
> Task :expo-file-system:packageReleaseResources
> Task :expo-image-loader:generateReleaseResValues
> Task :expo-image-loader:generateReleaseResources
> Task :expo-font:packageReleaseResources
> Task :expo-image-picker:generateReleaseResValues
> Task :expo-image-loader:packageReleaseResources
> Task :expo-image-picker:generateReleaseResources
> Task :expo-json-utils:generateReleaseResValues
> Task :expo-json-utils:generateReleaseResources
> Task :expo-image-picker:packageReleaseResources
> Task :expo-keep-awake:generateReleaseResValues
> Task :expo-json-utils:packageReleaseResources
> Task :expo-linking:generateReleaseResValues
> Task :expo-keep-awake:generateReleaseResources
> Task :expo-linking:generateReleaseResources
> Task :expo-keep-awake:packageReleaseResources
> Task :expo-manifests:generateReleaseResValues
> Task :expo-linking:packageReleaseResources
> Task :expo-manifests:generateReleaseResources
> Task :expo-modules-core:generateReleaseResValues
> Task :expo-modules-core:generateReleaseResources
> Task :expo-manifests:packageReleaseResources
> Task :expo-print:generateReleaseResValues
> Task :expo-modules-core:packageReleaseResources
> Task :expo-sharing:generateReleaseResValues
> Task :expo-print:generateReleaseResources
> Task :expo-sharing:generateReleaseResources
> Task :expo-dev-launcher:packageReleaseResources
> Task :expo-print:packageReleaseResources
> Task :expo-sharing:packageReleaseResources
> Task :expo-structured-headers:generateReleaseResValues
> Task :expo-updates-interface:generateReleaseResValues
> Task :expo-updates:generateReleaseResValues
> Task :expo-updates:generateReleaseResources
> Task :expo-structured-headers:generateReleaseResources
> Task :expo-updates-interface:generateReleaseResources
> Task :expo-updates:packageReleaseResources
> Task :expo-updates-interface:packageReleaseResources
> Task :expo-structured-headers:packageReleaseResources
> Task :react-native-gesture-handler:generateReleaseResValues
> Task :react-native-picker_picker:generateReleaseResValues
> Task :expo-web-browser:generateReleaseResValues
> Task :react-native-gesture-handler:generateReleaseResources
> Task :expo-web-browser:generateReleaseResources
> Task :react-native-picker_picker:generateReleaseResources
> Task :react-native-gesture-handler:packageReleaseResources
> Task :react-native-reanimated:generateReleaseResValues
> Task :expo-web-browser:packageReleaseResources
> Task :react-native-picker_picker:packageReleaseResources
> Task :react-native-safe-area-context:generateReleaseResValues
> Task :react-native-screens:generateReleaseResValues
> Task :react-native-reanimated:generateReleaseResources
> Task :react-native-safe-area-context:generateReleaseResources
> Task :react-native-reanimated:packageReleaseResources
> Task :react-native-svg:generateReleaseResValues
> Task :react-native-screens:generateReleaseResources
> Task :react-native-svg:generateReleaseResources
> Task :react-native-safe-area-context:packageReleaseResources
> Task :react-native-vector-icons:generateReleaseResValues
> Task :react-native-vector-icons:generateReleaseResources
> Task :react-native-svg:packageReleaseResources
> Task :expo:extractDeepLinksRelease
> Task :react-native-screens:packageReleaseResources
> Task :expo-application:extractDeepLinksRelease
> Task :react-native-vector-icons:packageReleaseResources
> Task :expo-asset:extractDeepLinksRelease
> Task :expo-asset:processReleaseManifest
> Task :expo-application:processReleaseManifest
> Task :expo:processReleaseManifest
> Task :expo-constants:extractDeepLinksRelease
> Task :expo-barcode-scanner:extractDeepLinksRelease
> Task :expo-camera:extractDeepLinksRelease
> Task :expo-constants:processReleaseManifest
> Task :expo-barcode-scanner:processReleaseManifest
> Task :expo-crypto:extractDeepLinksRelease
> Task :expo-camera:processReleaseManifest
> Task :expo-dev-client:extractDeepLinksRelease
> Task :expo-dev-launcher:extractDeepLinksRelease
> Task :expo-crypto:processReleaseManifest
> Task :expo-dev-menu:extractDeepLinksRelease
> Task :expo-dev-client:processReleaseManifest
> Task :expo-dev-launcher:processReleaseManifest
> Task :expo-eas-client:extractDeepLinksRelease
> Task :expo-dev-menu-interface:extractDeepLinksRelease
> Task :expo-dev-menu:processReleaseManifest
> Task :expo-file-system:extractDeepLinksRelease
> Task :expo-eas-client:processReleaseManifest
> Task :expo-dev-menu-interface:processReleaseManifest
> Task :expo-font:extractDeepLinksRelease
> Task :expo-image-loader:extractDeepLinksRelease
> Task :expo-image-loader:processReleaseManifest
> Task :expo-font:processReleaseManifest
> Task :expo-file-system:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-file-system/android/src/main/AndroidManifest.xml:6:9-8:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
> Task :expo-image-picker:extractDeepLinksRelease
> Task :expo-json-utils:extractDeepLinksRelease
> Task :expo-keep-awake:extractDeepLinksRelease
> Task :expo-keep-awake:processReleaseManifest
> Task :expo-json-utils:processReleaseManifest
> Task :expo-image-picker:processReleaseManifest
> Task :expo-linking:extractDeepLinksRelease
> Task :expo-modules-core:extractDeepLinksRelease
> Task :expo-manifests:extractDeepLinksRelease
> Task :expo-linking:processReleaseManifest
> Task :expo-manifests:processReleaseManifest
> Task :expo-modules-core:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/AndroidManifest.xml:8:9-11:45 Warning:
	meta-data#com.facebook.soloader.enabled@android:value was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
> Task :expo-sharing:extractDeepLinksRelease
> Task :expo-print:extractDeepLinksRelease
> Task :expo-structured-headers:extractDeepLinksRelease
> Task :expo-print:processReleaseManifest
> Task :expo-updates:extractDeepLinksRelease
> Task :expo-structured-headers:processReleaseManifest
> Task :expo-updates-interface:extractDeepLinksRelease
> Task :expo-sharing:processReleaseManifest
> Task :expo-updates:processReleaseManifest
> Task :expo-web-browser:extractDeepLinksRelease
> Task :expo-updates-interface:processReleaseManifest
> Task :react-native-gesture-handler:extractDeepLinksRelease
> Task :react-native-picker_picker:extractDeepLinksRelease
> Task :react-native-gesture-handler:processReleaseManifest
> Task :expo-web-browser:processReleaseManifest
> Task :react-native-safe-area-context:extractDeepLinksRelease
> Task :react-native-reanimated:extractDeepLinksRelease
> Task :react-native-picker_picker:processReleaseManifest
package="com.reactnativecommunity.picker" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/@react-native-picker/picker/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.picker" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/@react-native-picker/picker/android/src/main/AndroidManifest.xml.
> Task :react-native-screens:extractDeepLinksRelease
> Task :react-native-safe-area-context:processReleaseManifest
package="com.th3rdwave.safeareacontext" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.th3rdwave.safeareacontext" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
> Task :react-native-reanimated:processReleaseManifest
> Task :react-native-svg:extractDeepLinksRelease
> Task :react-native-vector-icons:extractDeepLinksRelease
> Task :react-native-screens:processReleaseManifest
package="com.swmansion.rnscreens" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-screens/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.rnscreens" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-screens/android/src/main/AndroidManifest.xml.
> Task :react-native-vector-icons:processReleaseManifest
package="com.oblador.vectoricons" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-vector-icons/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.oblador.vectoricons" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-vector-icons/android/src/main/AndroidManifest.xml.
> Task :react-native-svg:processReleaseManifest
package="com.horcrux.svg" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-svg/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.horcrux.svg" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-svg/android/src/main/AndroidManifest.xml.
> Task :expo-application:compileReleaseLibraryResources
> Task :expo-asset:compileReleaseLibraryResources
> Task :expo:compileReleaseLibraryResources
> Task :expo-asset:parseReleaseLocalResources
> Task :expo-application:parseReleaseLocalResources
> Task :expo:parseReleaseLocalResources
> Task :expo-asset:generateReleaseRFile
> Task :expo-application:generateReleaseRFile
> Task :expo:generateReleaseRFile
> Task :expo-barcode-scanner:compileReleaseLibraryResources
> Task :expo-camera:compileReleaseLibraryResources
> Task :expo-constants:compileReleaseLibraryResources
> Task :expo-barcode-scanner:parseReleaseLocalResources
> Task :expo-camera:parseReleaseLocalResources
> Task :expo-constants:parseReleaseLocalResources
> Task :expo-constants:generateReleaseRFile
> Task :expo-camera:generateReleaseRFile
> Task :expo-barcode-scanner:generateReleaseRFile
> Task :expo-crypto:compileReleaseLibraryResources
> Task :app:createBundleReleaseJsAndAssets
Starting Metro Bundler
> Task :expo-dev-client:compileReleaseLibraryResources
> Task :expo-crypto:parseReleaseLocalResources
> Task :expo-dev-client:parseReleaseLocalResources
> Task :expo-crypto:generateReleaseRFile
> Task :expo-dev-client:generateReleaseRFile
> Task :expo-dev-launcher:parseReleaseLocalResources
> Task :expo-dev-launcher:compileReleaseLibraryResources
> Task :expo-dev-launcher:generateReleaseRFile
> Task :expo-dev-menu-interface:compileReleaseLibraryResources
> Task :expo-dev-menu:parseReleaseLocalResources
> Task :expo-dev-menu-interface:parseReleaseLocalResources
> Task :expo-dev-menu:generateReleaseRFile
> Task :expo-dev-menu:compileReleaseLibraryResources
> Task :expo-eas-client:compileReleaseLibraryResources
> Task :expo-eas-client:parseReleaseLocalResources
> Task :expo-file-system:compileReleaseLibraryResources
> Task :expo-dev-menu-interface:generateReleaseRFile
> Task :expo-font:compileReleaseLibraryResources
> Task :expo-eas-client:generateReleaseRFile
> Task :expo-file-system:parseReleaseLocalResources
> Task :expo-image-loader:compileReleaseLibraryResources
> Task :expo-font:parseReleaseLocalResources
> Task :expo-file-system:generateReleaseRFile
> Task :expo-image-loader:parseReleaseLocalResources
> Task :expo-image-picker:compileReleaseLibraryResources
> Task :expo-font:generateReleaseRFile
> Task :expo-json-utils:compileReleaseLibraryResources
> Task :expo-image-loader:generateReleaseRFile
> Task :expo-image-picker:parseReleaseLocalResources
> Task :expo-keep-awake:compileReleaseLibraryResources
> Task :expo-image-picker:generateReleaseRFile
> Task :expo-json-utils:parseReleaseLocalResources
> Task :expo-keep-awake:parseReleaseLocalResources
> Task :expo-linking:compileReleaseLibraryResources
> Task :expo-linking:parseReleaseLocalResources
> Task :expo-json-utils:generateReleaseRFile
> Task :expo-keep-awake:generateReleaseRFile
> Task :expo-linking:generateReleaseRFile
> Task :expo-manifests:compileReleaseLibraryResources
> Task :expo-print:compileReleaseLibraryResources
> Task :expo-modules-core:compileReleaseLibraryResources
> Task :expo-manifests:parseReleaseLocalResources
> Task :expo-print:parseReleaseLocalResources
> Task :expo-modules-core:parseReleaseLocalResources
> Task :expo-manifests:generateReleaseRFile
> Task :expo-print:generateReleaseRFile
> Task :expo-modules-core:generateReleaseRFile
> Task :expo-sharing:compileReleaseLibraryResources
> Task :expo-structured-headers:compileReleaseLibraryResources
> Task :expo-updates:compileReleaseLibraryResources
> Task :expo-structured-headers:parseReleaseLocalResources
> Task :expo-updates:parseReleaseLocalResources
> Task :expo-sharing:parseReleaseLocalResources
> Task :expo-structured-headers:generateReleaseRFile
> Task :expo-sharing:generateReleaseRFile
> Task :expo-updates:generateReleaseRFile
> Task :expo-updates-interface:compileReleaseLibraryResources
> Task :react-native-gesture-handler:compileReleaseLibraryResources
> Task :expo-web-browser:compileReleaseLibraryResources
> Task :expo-updates-interface:parseReleaseLocalResources
> Task :react-native-gesture-handler:parseReleaseLocalResources
> Task :expo-web-browser:parseReleaseLocalResources
> Task :expo-updates-interface:generateReleaseRFile
> Task :react-native-gesture-handler:generateReleaseRFile
> Task :expo-web-browser:generateReleaseRFile
> Task :react-native-reanimated:compileReleaseLibraryResources
> Task :react-native-reanimated:parseReleaseLocalResources
> Task :react-native-picker_picker:parseReleaseLocalResources
> Task :react-native-picker_picker:compileReleaseLibraryResources
> Task :react-native-picker_picker:generateReleaseRFile
> Task :react-native-reanimated:generateReleaseRFile
> Task :react-native-safe-area-context:compileReleaseLibraryResources
> Task :react-native-svg:compileReleaseLibraryResources
> Task :react-native-safe-area-context:parseReleaseLocalResources
> Task :react-native-screens:parseReleaseLocalResources
> Task :react-native-safe-area-context:generateReleaseRFile
> Task :react-native-screens:generateReleaseRFile
> Task :react-native-screens:compileReleaseLibraryResources
> Task :expo:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-svg:parseReleaseLocalResources
> Task :react-native-vector-icons:compileReleaseLibraryResources
> Task :expo:generateReleaseBuildConfig
> Task :expo-application:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-vector-icons:parseReleaseLocalResources
> Task :expo-application:generateReleaseBuildConfig
> Task :expo-modules-core:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-svg:generateReleaseRFile
> Task :react-native-vector-icons:generateReleaseRFile
> Task :expo-asset:checkKotlinGradlePluginConfigurationErrors
> Task :expo-modules-core:generateReleaseBuildConfig
> Task :expo-asset:generateReleaseBuildConfig
> Task :expo-application:javaPreCompileRelease
> Task :expo-barcode-scanner:checkKotlinGradlePluginConfigurationErrors
> Task :expo-asset:javaPreCompileRelease
> Task :expo-camera:checkKotlinGradlePluginConfigurationErrors
> Task :expo-barcode-scanner:generateReleaseBuildConfig
> Task :expo-camera:generateReleaseBuildConfig
> Task :expo-barcode-scanner:javaPreCompileRelease
> Task :expo-constants:checkKotlinGradlePluginConfigurationErrors
> Task :expo-camera:javaPreCompileRelease
> Task :expo-crypto:checkKotlinGradlePluginConfigurationErrors
> Task :expo-crypto:generateReleaseBuildConfig
> Task :expo-constants:generateReleaseBuildConfig
> Task :expo-crypto:javaPreCompileRelease
> Task :expo-dev-client:checkKotlinGradlePluginConfigurationErrors
> Task :expo-constants:javaPreCompileRelease
> Task :expo-dev-launcher:checkKotlinGradlePluginConfigurationErrors
> Task :app:createBundleReleaseJsAndAssets
Android Bundled 2274ms index.ts (1242 modules)
Writing bundle output to: /home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
Writing sourcemap output to: /home/expo/workingdir/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
Copying 38 asset files
Done writing bundle output
Done writing sourcemap output
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
:3967:16: warning: the variable "SharedArrayBuffer" was not declared in function "from"
    if (typeof SharedArrayBuffer !== 'undefined' && (isInstance(value, Shared...
               ^~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:7856:23: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"
        return typeof DebuggerInternal !== 'undefined' && DebuggerInternal.sh...
                      ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:18230:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"
      setTimeout(function () {
      ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:16464:31: warning: the variable "nativeFabricUIManager" was not declared in anonymous function " 391#"
  var _nativeFabricUIManage = nativeFabricUIManager,
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:16492:21: warning: the variable "clearTimeout" was not declared in anonymous function " 391#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:16505:51: warning: the variable "RN$enableMicrotasksInReact" was not declared in anonymous function " 391#"
... "undefined" !== typeof RN$enableMicrotasksInReact && !!RN$enableMicrotask...
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:16506:47: warning: the variable "queueMicrotask" was not declared in anonymous function " 391#"
...otask = "function" === typeof queueMicrotask ? queueMicrotask : scheduleTi...
                                 ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:20927:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 391#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:22363:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25634:5: warning: the variable "fetch" was not declared in anonymous function " 614#"
fetch,
    ^~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25635:5: warning: the variable "Headers" was not declared in anonymous function " 614#"
    Headers,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25636:5: warning: the variable "Request" was not declared in anonymous function " 614#"
    Request,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25637:5: warning: the variable "Response" was not declared in anonymous function " 614#"
    Response
    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25794:24: warning: the variable "FileReader" was not declared in function "readBlobAsArrayBuffer"
      var reader = new FileReader();
                       ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25849:44: warning: the variable "URLSearchParams" was not declared in anonymous function " 625#"
...e if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body...
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25968:26: warning: the variable "AbortController" was not declared in anonymous function " 631#"
          var ctrl = new AbortController();
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26102:23: warning: the variable "XMLHttpRequest" was not declared in anonymous function " 635#"
        var xhr = new XMLHttpRequest();
                      ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25647:71: warning: the variable "self" was not declared in anonymous function " 617#"
...undefined' && globalThis || typeof self !== 'undefined' && self ||
                                      ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28517:26: warning: the variable "navigator" was not declared in anonymous function " 794#"
  "undefined" !== typeof navigator && undefined !== navigator.scheduling && u...
                         ^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28627:37: warning: the variable "MessageChannel" was not declared in anonymous function " 794#"
  };else if ("undefined" !== typeof MessageChannel) {
                                    ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28642:34: warning: the variable "nativeRuntimeScheduler" was not declared in anonymous function " 794#"
... = "undefined" !== typeof nativeRuntimeScheduler ? nativeRuntimeScheduler....
                             ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:38511:34: warning: the variable "requestAnimationFrame" was not declared in function "start 9#"
...    this._animationFrame = requestAnimationFrame(this.onUpdate.bind(this));
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:61863:9: warning: the variable "REACT_NAVIGATION_DEVTOOLS" was not declared in anonymous arrow function " 2069#"
        REACT_NAVIGATION_DEVTOOLS.set(refContainer.current, {
        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:68122:26: warning: the variable "ResizeObserver" was not declared in anonymous arrow function " 2285#"
var observer = new ResizeObserver(entries => {
                         ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:97897:11: warning: the variable "_WORKLET" was not declared in function "assertEasingIsWorklet"
      if (_WORKLET) {
          ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:99680:94: warning: the variable "location" was not declared in function "registerSensor 1#"
...(0, _PlatformChecker.isWeb)() && location.protocol !== 'https:' ? ' Make s...
                                    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:100142:12: warning: the variable "__reanimatedLoggerConfig" was not declared in function "replaceLoggerImplementation"
        ...__reanimatedLoggerConfig,
           ^~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:100743:26: warning: Direct call to eval(), but lexical scope is not supported.
            workletFun = eval('(' + initData.code + '\n)');
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:100766:112: warning: the variable "_toString" was not declared in function "valueUnpacker"
...recognized by value unpacker: "${_toString(objectToUnpack)}".`);
                                    ^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:117737:26: warning: the variable "structuredClone" was not declared in function "createAnimationWithInitialValues"
    var animationStyle = structuredClone(_config.AnimationsData[animationName...
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:118057:5: warning: the variable "document" was not declared in function "configureWebLayoutAnimations"
    document.getElementById(PREDEFINED_WEB_ANIMATIONS_ID) !== null) {
    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:118152:27: warning: the variable "HTMLElement" was not declared in function "findDescendantWithExitingAnimation"
    if (!(node instanceof HTMLElement)) {
                          ^~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:118178:24: warning: the variable "MutationObserver" was not declared in function "addHTMLMutationObserver"
    var observer = new MutationObserver(mutationsList => {
                       ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:118223:41: warning: the variable "getComputedStyle" was not declared in function "fixElementPosition"
...entBorderTopValue = parseInt(getComputedStyle(parent).borderTopWidth);
                                ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:122198:5: warning: the variable "jest" was not declared in arrow function "beforeTest"
    jest.useFakeTimers();
    ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:122775:26: warning: the variable "_getAnimationTimestamp" was not declared in function "computeEasingProgress"
      var elapsedTime = (_getAnimationTimestamp() - startingTimestamp) / 1000;
                         ^~~~~~~~~~~~~~~~~~~~~~
> Task :expo-dev-client:dataBindingMergeDependencyArtifactsRelease
> Task :expo-modules-core:javaPreCompileRelease
> Task :expo-dev-launcher:dataBindingMergeDependencyArtifactsRelease
> Task :expo-dev-client:dataBindingGenBaseClassesRelease
> Task :expo-dev-client:generateReleaseBuildConfig
> Task :expo-dev-client:javaPreCompileRelease
> Task :expo-dev-menu:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-menu:generateReleaseBuildConfig
> Task :expo-dev-menu-interface:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-menu-interface:generateReleaseBuildConfig
> Task :expo-dev-menu-interface:javaPreCompileRelease
> Task :expo-json-utils:checkKotlinGradlePluginConfigurationErrors
> Task :expo-json-utils:generateReleaseBuildConfig
> Task :expo-json-utils:javaPreCompileRelease
> Task :expo-manifests:checkKotlinGradlePluginConfigurationErrors
> Task :expo-manifests:generateReleaseBuildConfig
> Task :expo-manifests:javaPreCompileRelease
> Task :expo-dev-launcher:dataBindingGenBaseClassesRelease
> Task :expo-dev-menu:javaPreCompileRelease
> Task :expo-updates-interface:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-launcher:generateReleaseBuildConfig
> Task :expo-updates-interface:generateReleaseBuildConfig
> Task :expo-updates-interface:javaPreCompileRelease
> Task :expo-eas-client:checkKotlinGradlePluginConfigurationErrors
> Task :expo-dev-launcher:javaPreCompileRelease
> Task :expo-file-system:checkKotlinGradlePluginConfigurationErrors
> Task :expo-eas-client:generateReleaseBuildConfig
> Task :expo-file-system:generateReleaseBuildConfig
> Task :expo-eas-client:javaPreCompileRelease
> Task :expo-font:checkKotlinGradlePluginConfigurationErrors
> Task :expo-file-system:javaPreCompileRelease
> Task :expo-image-loader:checkKotlinGradlePluginConfigurationErrors
> Task :expo-image-loader:generateReleaseBuildConfig
> Task :expo-font:generateReleaseBuildConfig
> Task :expo-font:javaPreCompileRelease
> Task :expo-image-picker:checkKotlinGradlePluginConfigurationErrors
> Task :expo-image-loader:javaPreCompileRelease
> Task :expo-keep-awake:checkKotlinGradlePluginConfigurationErrors
> Task :expo-image-picker:generateReleaseBuildConfig
> Task :expo-keep-awake:generateReleaseBuildConfig
> Task :expo-image-picker:javaPreCompileRelease
> Task :expo-linking:checkKotlinGradlePluginConfigurationErrors
> Task :expo-keep-awake:javaPreCompileRelease
> Task :expo-print:checkKotlinGradlePluginConfigurationErrors
> Task :expo-linking:generateReleaseBuildConfig
> Task :expo-print:generateReleaseBuildConfig
> Task :expo-linking:javaPreCompileRelease
> Task :expo-sharing:checkKotlinGradlePluginConfigurationErrors
> Task :expo-print:javaPreCompileRelease
> Task :expo-structured-headers:checkKotlinGradlePluginConfigurationErrors
> Task :expo-sharing:generateReleaseBuildConfig
> Task :expo-structured-headers:generateReleaseBuildConfig
> Task :expo-sharing:javaPreCompileRelease
> Task :expo-updates:checkKotlinGradlePluginConfigurationErrors
> Task :expo-structured-headers:javaPreCompileRelease
> Task :expo-web-browser:checkKotlinGradlePluginConfigurationErrors
> Task :expo-updates:generateReleaseBuildConfig
> Task :expo-web-browser:generateReleaseBuildConfig
> Task :expo-web-browser:javaPreCompileRelease
> Task :expo:javaPreCompileRelease
> Task :react-native-gesture-handler:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-gesture-handler:generateReleaseBuildConfig
> Task :react-native-reanimated:generateReleaseBuildConfig
> Task :react-native-reanimated:javaPreCompileRelease
> Task :react-native-reanimated:packageNdkLibs NO-SOURCE
> Task :expo-updates:javaPreCompileRelease
> Task :react-native-gesture-handler:javaPreCompileRelease
> Task :react-native-picker_picker:generateReleaseBuildConfig
> Task :react-native-picker_picker:javaPreCompileRelease
> Task :app:checkReleaseAarMetadata
> Task :app:generateReleaseResValues
> Task :app:mapReleaseSourceSetPaths
> Task :app:generateReleaseResources
> Task :react-native-picker_picker:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :react-native-reanimated:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :app:packageReleaseResources
> Task :react-native-reanimated:bundleLibCompileToJarRelease
> Task :app:parseReleaseLocalResources
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :app:mergeReleaseResources
> Task :react-native-picker_picker:bundleLibCompileToJarRelease
> Task :react-native-safe-area-context:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-safe-area-context:generateReleaseBuildConfig
> Task :app:processReleaseMainManifest
/home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
> Task :app:processReleaseManifest
> Task :app:processReleaseManifestForPackage
> Task :expo-modules-core:compileReleaseKotlin
> Task :app:processReleaseResources FAILED
> Task :react-native-safe-area-context:compileReleaseKotlin
w: file:///home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:27:11 'constructor ReactModuleInfo(String, String, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. use ReactModuleInfo(String, String, boolean, boolean, boolean, boolean)]
w: file:///home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:33:27 'getter for hasConstants: Boolean' is deprecated. This property is unused and it's planning to be removed in a future version of
        React Native. Please refrain from using it.
w: file:///home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.kt:59:23 'getter for uiImplementation: UIImplementation!' is deprecated. Deprecated in Java
> Task :react-native-gesture-handler:compileReleaseKotlin
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt:69:42 'constructor ReactModuleInfo(String, String, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. use ReactModuleInfo(String, String, boolean, boolean, boolean, boolean)]
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/FlingGestureHandler.kt:25:26 Parameter 'event' is never used
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt:72:62 The corresponding parameter in the supertype 'ViewGroupManager' is named 'borderRadius'. This may cause problems when calling this function with named arguments.
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt:77:63 The corresponding parameter in the supertype 'ViewGroupManager' is named 'borderRadius'. This may cause problems when calling this function with named arguments.
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt:82:65 The corresponding parameter in the supertype 'ViewGroupManager' is named 'borderRadius'. This may cause problems when calling this function with named arguments.
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.kt:87:66 The corresponding parameter in the supertype 'ViewGroupManager' is named 'borderRadius'. This may cause problems when calling this function with named arguments.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: /home/expo/workingdir/build/android/app/src/main/res/drawable/ic_launcher_background.xml:4: AAPT: error: resource drawable/splashscreen_logo (aka com.daniel2032.inventoryapp:drawable/splashscreen_logo) not found.
         
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 3m
451 actionable tasks: 451 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by Eiyel24** [comment]
can you help me with this splashscreen_logo


<img width="713" alt="Image" src="https://github.com/user-attachments/assets/5f5ac074-57cc-4edb-9a7b-c23bd7fd8b75" />

**Comment by csulit** [comment]
Our application runs smoothly without any errors in the development build. We haven't added or updated any dependencies, nor have we made any major changes to the current project. The only modification we've made is upgrading our EAS CLI to the latest version. After releasing the app to TestFlight, however, it crashes as soon as we try to open it. Strangely, no error is logged in Sentry. Additionally, we noticed that our Expo project in Bitbucket unexpectedly grew to 130MB, and we don't know why. This sudden increase is a mystery to us, and we're uncertain if it's related to the crash or the EAS CLI upgrade.

**Comment by sjchmiela** [comment]
Hey @csulit, may I ask you to open a new issue or create a Discord thread under #eas-help and mention me? Upgrading `eas-cli` shouldn't cause Git repository to grow — it's just a CLI, unless you unignored some files and started tracking them I see no reason for repo to change.

Same for @Eiyel24 — was it successfully building on `eas-cli@^14`? Can you try `npm i -g eas-cli@^14`, trigger a build again and see if the issue persists, and if it doesn't, let me know?

**Comment by csulit** [comment]
> Hey [@csulit](https://github.com/csulit), may I ask you to open a new issue or create a Discord thread under #eas-help and mention me? Upgrading `eas-cli` shouldn't cause Git repository to grow — it's just a CLI, unless you unignored some files and started tracking them I see no reason for repo to change.
> 
> Same for [@Eiyel24](https://github.com/Eiyel24) — was it successfully building on `eas-cli@^14`? Can you try `npm i -g eas-cli@^14`, trigger a build again and see if the issue persists, and if it doesn't, let me know?

I'll create a discord thread.

**Comment by knksmith57** [comment]
pretty sure this is still an issue?

**Comment by bmorgan365** [comment]
Still present for me in v16.7.2

I was only able to build by downgrading to v14.7.1

**Comment by nimesh-oss** [comment]
yup still the same idk what they fixed

**Comment by nimesh-oss** [comment]
> Still present for me in v16.7.2
> 
> I was only able to build by downgrading to v14.7.1

its still failing for me even on v14.7.1
