### ISSUE TITLE
Unable to build my project on EAS, met with unhelpful error "spawn pod ENOENT"

### ISSUE THREAD

**Issue by harrisrobin** [expo/eas-cli#816]
### Summary

Not sure if this is the right place for this, but there is no clear support channel for EAS (I have been a paying customer on 2 different projects throughout the entire early beta before the recent pricing changes). 

Right now, when I try the following command: 
```sh
eas build -p iOS
```

The build fails on EAS, all I get is an unhelpful error that says "spawn pod ENOENT" for both pods and the build:
<img width="1321" alt="CleanShot 2021-12-03 at 11 33 29@2x" src="https://user-images.githubusercontent.com/3880008/144588199-eb920c3a-fb45-46fe-8dd5-df3215901ee4.png">

Here is the build URL:

https://expo.dev/accounts/bridgeapp/projects/bridgecrypto/builds/39267dea-efc9-454c-ae1e-1e0e3511ed03

~The weird thing is, `expo prebuild` works just fine so I'm not sure what I can do to debug this further.~

cc: @quinlanj 

### Environment

```sh
  EAS CLI 0.38.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.volta/tools/image/node/14.18.1/bin/node
      Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 6.14.15 - ~/.volta/tools/image/node/14.18.1/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
```

### Error output

Install Pods
```sh
Installing pods
spawn pod ENOENT
```

Fail Build
```
Build failed
spawn pod ENOENT
```

### Reproducible demo or steps to reproduce from a blank project

I'm not sure how I would go about putting this, happens specifically on our project/account which you can find using this build URL:

https://expo.dev/accounts/bridgeapp/projects/bridgecrypto/builds/39267dea-efc9-454c-ae1e-1e0e3511ed03

**Comment by dsokal** [comment]
Hi @harrisrobin,
Thanks for reporting. I took a look at the build logs you provided and it seems that you're trying to build a bare project. You mentioned that `expo prebuild` works fine so I assume you've run it before `eas build`.

1. Are you sure that the project you're trying to build with EAS Build can be built locally?
2. Can you `cd` into the `ios` directory of your project and try to run `pod install`?
3. Can you please share your eas.json?

**Comment by harrisrobin** [comment]
@dsokal  you're right, expo prebuild does not work my bad.

Upon trying again, I get this: 
```sh
Error: There is neither a value or a policy set for the runtime version on "android"
    at getRuntimeVersion (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/utils/Updates.ts:95:11)
    at getRuntimeVersionNullable (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/utils/Updates.ts:77:12)
    at setVersionsConfig (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/android/Updates.ts:100:26)
    at setUpdatesConfig (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/android/Updates.ts:91:10)
    at action (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/android/Updates.ts:33:25)
    at action (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at nextMod (/Users/harris/workspace/groupegrifflin/bridge/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/Users/harris/.volta/tools/image/packages/expo-cli/lib/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
    at async interceptingMod (/Users/harris/.volta/tools/image/packages/expo-cli/lib/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
```

<img width="1141" alt="CleanShot 2021-12-03 at 14 31 52@2x" src="https://user-images.githubusercontent.com/3880008/144610768-da486ca8-65bc-47e9-a778-bfb32a30bf43.png">


I ran into this error many times, I still don't have a solution and googling doesn't really give me anything useful. I'm not really sure what this error is trying to tell me other than Expo wasn't able to compute my runtime version automatically? Posted about it on [Discord](https://discord.com/channels/695411232856997968/809586753719238656/916013224946729042) as well. 

here's my app.config.ts

```ts
/* eslint-disable import/no-anonymous-default-export */
import "dotenv/config"
import { ExpoConfig, ConfigContext } from "@expo/config"

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  owner: "redacted",
  name: "REDACTED",
  slug: "redacted",
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "redacted",
  userInterfaceStyle: "automatic",
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    buildNumber: "8",
    config: {
      usesNonExemptEncryption: false,
    },
    supportsTablet: false,
    bundleIdentifier: "REDACTED",
    googleServicesFile: "./google/GoogleService-Info.plist",
    associatedDomains: ["REDACTED"],
    splash: {
      backgroundColor: "#14161E",
      image: "./assets/images/ios_splash.png",
      resizeMode: "contain",
    },
    usesAppleSignIn: true,
  },
  android: {
    adaptiveIcon: {
      foregroundImage: "./assets/images/adaptive-icon.png",
      backgroundColor: "#ffffff",
    },
    package: "REDACTED",
    jsEngine: "jsc",
    googleServicesFile: "./google/google-services.json",
    versionCode: 8,
    intentFilters: [
      {
        action: "VIEW",
        data: [
          {
            scheme: "https",
            host: "REDACTED",
          },
        ],
        category: ["BROWSABLE", "DEFAULT"],
      },
      {
        action: "VIEW",
        data: [
          {
            scheme: "https",
            host: "REDACTED",
          },
        ],
        category: ["BROWSABLE", "DEFAULT"],
      },
    ],
    splash: {
      backgroundColor: "#0c0f18",
      resizeMode: "cover",
      image: "./assets/images/android_splash_ldpi.png",
      mdpi: "./assets/images/android_splash_mdpi.png",
      hdpi: "./assets/images/android_splash_hdpi.png",
      xhdpi: "./assets/images/android_splash_xhdpi.png",
      xxhdpi: "./assets/images/android_splash_xxhdpi.png",
      xxxhdpi: "./assets/images/android_splash_xxxhdpi.png",
    },
  },
  web: {
    favicon: "./assets/images/favicon.png",
    config: {
      firebase: "REDACTED"
    },
  },
  plugins: [
    "sentry-expo",
    [
      "./react-native-branch-plugin",
      { apiKey: "REDACTED" },
    ],
  ],
  hooks: {
    postPublish: [
      {
        file: "sentry-expo/upload-sourcemaps",
        config: {
          organization: "REDACTED",
          project: "REDACTED",
          authToken: "REDACTED"
        },
      },
    ],
  },
  extra: "REDACTED"
})

```


Let me know what steps I can take from here, thank you 😄

**Comment by dsokal** [comment]
- What version of expo-cli do you have? If it's not the latest, try upgrading, and then run `expo prebuild`.
- I know it's not related to the issue but why do you need to run `expo prebuild`? EAS Build can build your Expo managed project out of the box.

**Comment by harrisrobin** [comment]
1. @dsokal its the latest: 
<img width="401" alt="CleanShot 2021-12-03 at 14 53 41@2x" src="https://user-images.githubusercontent.com/3880008/144613851-53272ccd-c7a2-4b90-80ad-c6dbcce7363f.png">

2. @dsokal no I don't need to, but im assuming that when I try to build the project with EAS on expo cloud this is the error that is making it fail, but as mentioned before all I see is "spawn pod ENOENT". Me running prebuild was simply trying to diagnose why my build fails on EAS cloud 😓

**Comment by harrisrobin** [comment]
@dsokal trying to run EAS Build locally gives me the same error basically: 

When I run:
`EAS_LOCAL_BUILD_SKIP_CLEANUP=1 EXPO_DEBUG=1 eas build -p ios --local`

I get: 
<img width="1138" alt="CleanShot 2021-12-03 at 14 56 58@2x" src="https://user-images.githubusercontent.com/3880008/144614350-ed94ab90-f815-47f6-8c3b-16a3c0e82d4d.png">


to me it looks like [withRuntimeVersion](https://github.com/expo/expo-cli/blob/c24263b4df40c4d592ff0c5b7b904f261f9a949a/packages/config-plugins/src/utils/Updates.ts#L52-L71) doesn't compute my runtime basically, and it's asking me to set a policy for it which I shouldn't need to as far as I know.

**Comment by dsokal** [comment]
> no I don't need to, but im assuming that when I try to build the project with EAS on expo cloud this is the error that is making it fail, but as mentioned before all I see is "spawn pod ENOENT". Me running prebuild was simply trying to diagnose why my build fails with EAS 😓

I don't know if I follow but the build logs you shared in the first message are already from a project that has been prebuilt. Have you tried to build the project in the state where `android` and `ios` directories do not exist?

**Comment by dsokal** [comment]
@jkhales do you know what could be causing this?

**Comment by harrisrobin** [comment]
@dsokal I don't see where I shared build logs from a project that is already prebuilt? 

I shared a build URL to expo cloud that shows a failing build on expo cloud and I also shared some errors I run into when I try to use EAS to build locally with some more info/context. 

>Have you tried to build the project in the state where android and ios directories do not exist?

I mean, isn't that what's happening when I try to build with EAS locally or on the cloud? The android and iOS directories do not exist, and I run into the error above.

**Comment by jkhales** [comment]
taking a look at this

**Comment by jkhales** [comment]
@harrisrobin would mind confirming that your `eas-cli` (in addition to your `expo-cli`, which I see you posted above) is up to date?

This issue should have been fixed here: https://github.com/expo/eas-cli/pull/785 and publish in version >= `0.38.0`: https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#-bug-fixes-4

**Comment by jkhales** [comment]
My suspicion is that there is some improper cacheing happening in your local env. 

To confirm, you have installed both eas and expo globally? 

Have you tried nuking your projects node_modues, `rm -rf node_modules` and re `yarn`ing`?

Is there an outdate eas installed in your project? (check the package.json)

**Comment by harrisrobin** [comment]
@jkhales 
* Both eas-cli and expo-cli were up to date during my tests (attached screenshot for expo-cli)
* eas-cli & expo-cli both installed globally using `yarn global add` command.
* Can confirm I still face this despite all that: 
<img width="1135" alt="CleanShot 2021-12-03 at 19 01 20@2x" src="https://user-images.githubusercontent.com/3880008/144650759-d0af993a-ad3e-411c-a23f-72a9fdb249dc.png">


One thing that comes to mind is, I am working in a monorepo. Do you think that has any bearing on this issue? 

<img width="913" alt="CleanShot 2021-12-03 at 18 59 14@2x" src="https://user-images.githubusercontent.com/3880008/144650502-f0e02818-d5f8-4174-86c1-135fc6c93d02.png">

FYI, here's my package.json as well:
```json
{
  "name": "bridge-mobile",
  "version": "0.1.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll=false",
    "build": "scripty",
    "prepare": "yarn run infinite-flatlist-patch",
    "postinstall": "cd ../.. && yarn patch-package && yarn build",
    "postuninstall": "yarn run infinite-flatlist-patch",
    "ios:beta": "expo build:ios -t simulator",
    "eas:build-ios": "EXPO_DEBUG=1 eas build -p ios --non-interactive",
    "eas:submit-ios": "EXPO_DEBUG=1 eas submit -p ios --latest",
    "eas:build-android": "EXPO_DEBUG=1 eas build -p android --non-interactive",
    "eas:submit-android": "EXPO_DEBUG=1 eas submit -p android --latest"
  },
  "scripty": {
    "path": "../../scripts/packages"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@bridge/ui": "*",
    "@burstware/expo-plaid-link": "^1.0.6",
    "@expo/vector-icons": "^12.0.0",
    "@gorhom/bottom-sheet": "^4.1.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.2",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "6.0.1",
    "@react-navigation/native": "~6.0.1",
    "@react-navigation/native-stack": "^6.0.2",
    "@react-navigation/stack": "~6.0.1",
    "@types/lodash.debounce": "^4.0.6",
    "date-fns": "^2.27.0",
    "dotenv": "^10.0.0",
    "expo": "^43.0.0",
    "expo-apple-authentication": "~4.0.3",
    "expo-application": "~4.0.0",
    "expo-asset": "~8.4.3",
    "expo-auth-session": "~3.4.2",
    "expo-constants": "~12.1.3",
    "expo-contacts": "~10.0.3",
    "expo-dev-client": "^0.6.3",
    "expo-device": "~4.0.3",
    "expo-firebase-analytics": "~5.0.3",
    "expo-firebase-core": "~4.0.3",
    "expo-font": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-localization": "11.0.0",
    "expo-random": "~12.0.1",
    "expo-sms": "~10.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "expo-web-browser": "~10.0.3",
    "firebase": "8.10.0",
    "libphonenumber-js": "^1.9.23",
    "lodash.groupby": "^4.6.0",
    "mobx": "^6.3.2",
    "mobx-react-lite": "^3.2.0",
    "mobx-state-tree": "^5.0.2",
    "numeral": "^2.0.6",
    "rambdax": "^7.4.1",
    "ramda": "^0.27.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-branch": "5.0.0",
    "react-native-exception-handler": "^2.10.10",
    "react-native-gesture-handler": "~1.10.3",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-reanimated": "~2.2.0",
    "react-native-redash": "^16.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0",
    "sentry-expo": "^4.0.0",
    "validate.js": "^0.13.1",
    "world-countries": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@sentry/cli": "^1.68.0",
    "@types/lodash.groupby": "^4.6.6",
    "@types/numeral": "^2.0.1",
    "@types/ramda": "^0.27.44",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "babel-eslint": "^10.1.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-plugin-flowtype": "^5.9.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest-expo": "^43.0.0",
    "react-native-infinite-flatlist-patch": "^1.1.0",
    "reactotron-mst": "^3.1.3",
    "reactotron-react-native": "^5.0.0",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

**Comment by harrisrobin** [comment]
@jkhales another thing to note, we have a custom expo plugin to integrate branch SDK, but I don't see how that could affect it but just wanted to put that out there just incase.

**Comment by harrisrobin** [comment]
@jkhales looks like the reason this was failing is because of `react-native.config.js` that was just there as a build artifact from running `expo prebuild`. 


I deleted `react-native.config.js` and now my build was successful.

@jkhales @dsokal maybe there's a better way to handle this if `react-native.config.js` is detected in a project? This seems like something that's easy to miss, so I think EAS probably assumed this was a regular RN project.

**Comment by jkhales** [comment]
> @jkhales looks like the reason this was failing is because of `react-native.config.js` that was just there as a build artifact from running `expo prebuild`.
> 
> I deleted `react-native.config.js` and now my build was successful.
> 
> @jkhales @dsokal maybe there's a better way to handle this if `react-native.config.js` is detected in a project? This seems like something that's easy to miss, so I think EAS probably assumed this was a regular RN project.

Oh, that sounds frustrating. Happy you found it! Good idea about that check, will look into it.

**Comment by brentvatne** [comment]
@harrisrobin - we're removing react-native.config.js from the expo-dev-client config plugin - https://github.com/expo/expo/pull/15380

**Comment by brentvatne** [comment]
also, @harrisrobin, it'd be helpful if you could detail how you got into this state, and also share the contents of your react-native.config.js. it's not clear to me why this file was leading to the error that you encountered.

**Comment by harrisrobin** [comment]
@brentvatne this file was generated along with the `ios` and `android` after I ran `expo prebuild` in order to debug an issue I was having with EAS. I deleted the `iOS` and `android` folders but missed `react-native.config.js`. 

Here are the contents: 
```js
// File created by expo-dev-client/app.plugin.js

module.exports = {
  dependencies: {
    ...require('expo-dev-client/dependencies'),
  },
};
```

Let me know if there's anything I can do to help you, but it's clear to me that this file is what caused my issue as having it leads to the above error which I can reproduce.

**Comment by harrisrobin** [comment]
@brentvatne just tried again, I added the `react-native.config.js` file and got the same error again: 
<img width="892" alt="CleanShot 2021-12-03 at 22 34 18@2x" src="https://user-images.githubusercontent.com/3880008/144675698-b303423c-3cb6-432f-ada8-5c1c2e5103b2.png">

**Comment by harrisrobin** [comment]
Another thing I noticed, every time I run `expo prebuild` it duplicates an import statement in index.js:
![CleanShot 2021-12-03 at 22 35 40@2x](https://user-images.githubusercontent.com/3880008/144675848-21590541-d3b3-4423-b692-686c5792d0de.png)

It doesn't seem to detect that it's already there, I constantly have to remove the extra import.

**Comment by brentvatne** [comment]
> @brentvatne just tried again, I added the `react-native.config.js` file and got the same error again: <img alt="CleanShot 2021-12-03 at 22 34 18@2x" width="892" src="https://user-images.githubusercontent.com/3880008/144675698-b303423c-3cb6-432f-ada8-5c1c2e5103b2.png">

this error seems related to your eas-cli version, right? it doesn't seem to have anything to do with react-native.config.js

> I think in general, running expo prebuild has broken eas for me several times

do you find yourself running it multiple times? prebuild is intended to only be run once, and results may not work as expected if you run prebuild on top of a project stat where you have already run prebuild - as you've observed. cc @EvanBacon - maybe we should add a warning here

**Comment by harrisrobin** [comment]
> > @brentvatne just tried again, I added the `react-native.config.js` file and got the same error again: <img alt="CleanShot 2021-12-03 at 22 34 18@2x" width="892" src="https://user-images.githubusercontent.com/3880008/144675698-b303423c-3cb6-432f-ada8-5c1c2e5103b2.png">
> 
> this error seems related to your eas-cli version, right? it doesn't seem to have anything to do with react-native.config.js
> 


@brentvatne maybe you're right and it's not related to react-native.config.js, not really sure at this point. However, my CLI version is up to date.

> > I think in general, running expo prebuild has broken eas for me several times
> 
> do you find yourself running it multiple times? prebuild is intended to only be run once, and results may not work as expected if you run prebuild on top of a project stat where you have already run prebuild - as you've observed. cc @EvanBacon - maybe we should add a warning here

Yeah I do, whenever I need to debug why my build fails on EAS and I don't get a clear error, it's easier for me to run `expo prebuild` and open the app in Xcode myself.

**Comment by brentvatne** [comment]
> Yeah I do, whenever I need to debug why my build fails on EAS and I don't get a clear error, it's easier for me to run expo prebuild and open the app in Xcode myself.

that's fine! you should do that. run `expo prebuild --clean` to avoid re-applying plugins on a dirty project
